### ISSUE TITLE
hay/markov not on packagist

### ISSUE THREAD

**Issue by eenblam** [eenblam/devops-2#1]
It seems to be the most popular PHP Markov chain library on GitHub (by Stars,) but it's not available for Composer on Packagist.

**Comment by Serpent999** [comment]
What are the alternatives?

**Comment by eenblam** [comment]
See [heidilabs/markov-php]https://packagist.org/packages/heidilabs/markov-php)
and its [source](https://github.com/heidilabs/markov-php).
